import logging
import time
from typing import List
from openai import OpenAI, APIError, APITimeoutError, RateLimitError
import config as cfg
from models import TranscriptSegment

logger = logging.getLogger(__name__)

_client: OpenAI | None = None

SOP_SYSTEM_PROMPT = """You are an expert meeting analyst and technical writer.
Given a meeting transcript with speaker labels, produce a professional Standard Operating Procedure (SOP) / Meeting Summary document in Markdown.

Structure your output EXACTLY as follows:

# [Meeting Title] — Meeting Summary

**Date:** [date]
**Participants:** [comma-separated list of unique speakers]
**Duration:** [estimated duration]

---

## 1. Meeting Overview
[2-3 sentence summary of the meeting's purpose and outcome]

## 2. Agenda Items Discussed
[Bullet list of main topics covered]

## 3. Key Decisions Made
[Numbered list of concrete decisions reached]

## 4. Action Items
| Owner | Action | Due |
|-------|--------|-----|
[Table rows for each action item extracted from transcript]

## 5. Detailed Discussion Notes
[Section-by-section breakdown of the discussion, preserving speaker attribution for important points]

## 6. Next Steps
[Ordered list of follow-up items]

## 7. Reference Screenshots
[Note the count of screenshots captured and any described content]

---
*Generated by Notetaker — Powered by NVIDIA Llama-3.1-Nemotron-70B*

Be precise, professional, and concise. Infer real names from labels like SPEAKER_00 when context provides clues."""


def _get_client() -> OpenAI:
    global _client
    if _client is None:
        # Always read live from cfg — picks up runtime config updates
        _client = OpenAI(
            api_key=cfg.NVIDIA_NIM_API_KEY,
            base_url=cfg.NVIDIA_NIM_BASE_URL,
            timeout=60.0,
        )
    return _client


def reset_client() -> None:
    global _client
    _client = None


def _format_transcript(segments: List[TranscriptSegment]) -> str:
    lines = []
    for seg in segments:
        ts = f"[{int(seg.start // 60):02d}:{int(seg.start % 60):02d}]"
        lines.append(f"{ts} **{seg.speaker}:** {seg.text}")
    return "\n".join(lines)


def generate_sop(
    segments: List[TranscriptSegment],
    screenshots: List[str],
    meeting_title: str,
    meeting_date: str,
    host_name: str = "",
    max_retries: int = 3,
) -> str:
    client = _get_client()
    transcript_text = _format_transcript(segments)

    screenshot_note = ""
    if screenshots:
        screenshot_note = (
            f"\n\n## Screenshots ({len(screenshots)} captured during meeting)\n"
            + "\n".join(
                f"- Screenshot {i + 1}: captured at meeting timestamp" for i in range(len(screenshots))
            )
        )

    user_text = (
        f"Meeting Title: {meeting_title}\n"
        f"Date: {meeting_date}\n"
        f"Host: {host_name}\n\n"
        f"## Transcript\n\n{transcript_text}"
        f"{screenshot_note}"
    )

    last_error: Exception | None = None
    for attempt in range(max_retries):
        try:
            response = client.chat.completions.create(
                model=cfg.NVIDIA_NIM_MODEL,
                messages=[
                    {"role": "system", "content": SOP_SYSTEM_PROMPT},
                    {"role": "user", "content": user_text},
                ],
                temperature=0.2,
                max_tokens=4096,
            )
            content = response.choices[0].message.content or ""
            if not content:
                raise ValueError("NIM returned empty response")
            return content

        except RateLimitError as e:
            wait = 2 ** attempt
            logger.warning("NIM rate limited (attempt %d) — retrying in %ds", attempt + 1, wait)
            time.sleep(wait)
            last_error = e

        except APITimeoutError as e:
            logger.warning("NIM timeout (attempt %d)", attempt + 1)
            last_error = e

        except APIError as e:
            logger.error("NIM API error: %s", e)
            raise RuntimeError(f"NVIDIA NIM API error: {e}") from e

    raise RuntimeError(f"NIM failed after {max_retries} attempts: {last_error}")
