"""Auth endpoints — mocks Google OAuth flow."""
import pytest
from unittest.mock import patch, MagicMock
import os


def test_auth_status_not_authenticated(client):
    with patch("routers.auth.get_credentials", return_value=None):
        r = client.get("/api/auth/status")
    assert r.status_code == 200
    assert r.json()["authenticated"] is False


def test_auth_status_authenticated(client):
    mock_creds = MagicMock()
    mock_creds.valid = True
    with patch("routers.auth.get_credentials", return_value=mock_creds), \
         patch("routers.auth.get_authenticated_email", return_value="user@gmail.com"):
        r = client.get("/api/auth/status")
    assert r.status_code == 200
    body = r.json()
    assert body["authenticated"] is True
    assert body["email"] == "user@gmail.com"


def test_auth_google_missing_credentials(client, tmp_path):
    """Returns 500 if credentials.json doesn't exist."""
    with patch("routers.auth.GOOGLE_CREDENTIALS_FILE", str(tmp_path / "missing.json")):
        r = client.get("/api/auth/google")
    assert r.status_code == 500
    assert "credentials.json" in r.json()["detail"]


def test_auth_google_returns_url(client, tmp_path):
    """Returns auth_url when credentials.json is present."""
    creds_file = tmp_path / "credentials.json"
    creds_file.write_text('{"installed": {}}')
    mock_flow = MagicMock()
    mock_flow.authorization_url.return_value = ("https://accounts.google.com/o/oauth2/auth?...", "state")
    with patch("routers.auth.GOOGLE_CREDENTIALS_FILE", str(creds_file)), \
         patch("routers.auth.get_flow", return_value=mock_flow):
        r = client.get("/api/auth/google")
    assert r.status_code == 200
    assert "auth_url" in r.json()


def test_auth_callback_invalid_state(client):
    """Callback with no/wrong state is rejected (CSRF guard)."""
    r = client.get("/api/auth/callback?code=validcode&state=bogus")
    assert r.status_code == 400
    assert "state" in r.json()["detail"].lower()


def test_auth_callback_valid_state(client, tmp_path):
    """Callback with a state generated by /auth/google succeeds."""
    creds_file = tmp_path / "credentials.json"
    creds_file.write_text('{"installed": {}}')

    mock_flow = MagicMock()
    mock_flow.authorization_url.return_value = ("https://accounts.google.com/...", "")

    # First get the state by calling /auth/google
    with patch("routers.auth.GOOGLE_CREDENTIALS_FILE", str(creds_file)), \
         patch("routers.auth.get_flow", return_value=mock_flow):
        start_r = client.get("/api/auth/google")
    assert start_r.status_code == 200

    # Extract state from the stored dict (injected via mock)
    from routers.auth import _oauth_states
    state = next(iter(_oauth_states))

    with patch("routers.auth.save_credentials_from_code", return_value=MagicMock()):
        r = client.get(f"/api/auth/callback?code=authcode&state={state}",
                       follow_redirects=False)
    assert r.status_code in (200, 302, 307)
